# travis ci configuration

language: node_js

node_js:
  - "10.15.3"

before_install:
  - openssl aes-256-cbc -K $encrypted_36ffc1369fbc_key -iv $encrypted_36ffc1369fbc_iv -in .travis/travis_rsa.enc -out .travis/travis_rsa -d

install:
  - npm install

script:
  - npm test
  - touch testing.travis
  - npm run build
  # - npm run crawl

after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/travis
  - ssh-add .travis/travis_rsa
  - git add testing.travis
  - git commit -m ":: travis automated commit ::"
  - git remote add deploy git@github.com:Neko250/rlscrapper.git
  - git push deploy

# deploy:
#   provider: pages
#   skip_cleanup: true
#   github_token: $GITHUB_TOKEN
#   keep_history: true
#   local_dir: dist/
#   fqdn: rlspain.cf
#   target_branch: gh-pages
#   on:
#     branch: master
