language: node_js

node_js:
  - 10.15.3

before_install:
  - openssl aes-256-cbc -K $encrypted_f73abf23e737_key -iv $encrypted_f73abf23e737_iv -in .travis/travis_rsa.enc -out .travis/travis_rsa -d

install:
  - npm install

script:
  - npm test
  - npm run build

after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/travis_rsa
  - ssh-add .travis/travis_rsa
  - git checkout master
  - ls dist/
  # - git commit -m "travis automated commit"
  # - git remote add deploy git@github.com:Neko250/rlscrapper.git
  # - git push deploy master
