language: node_js

node_js:
  - 10.15.3

before_install:
  - openssl aes-256-cbc -K $encrypted_f73abf23e737_key -iv $encrypted_f73abf23e737_iv -in .travis/travis_rsa.enc -out .travis/travis_rsa -d

install:
  - npm install

script:
  - npm test

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL

before_deploy:
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/travis_rsa
  - ssh-add .travis/travis_rsa
  - git checkout master
  - npm run crawl
  - npm run build
  - git add assets/data/db.json
  - git commit -m "travis db update"
  - git remote add deploy git@github.com:Neko250/rlscrapper.git
  - git push deploy master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  keep_history: false
  local_dir: dist/
  fqdn: rlspain.cf
  on:
    branch: master
